### ISSUE TITLE
Run benchmarks on multiple JVMs

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/entity-system-benchmarks#11]
As implied in https://github.com/junkdog/artemis-odb/issues/214 running this on multiple JVMs might be valuable. Or perhaps limit to just stating the JVM in the benchmark results.

**Comment by junkdog** [comment]
+1 for stating JVM version

Running on multiple JVM:s/OS configurations would be interesting but ultimately, I'd take too  much time. Iirc, the existing benchmark suite takes ~2h. A couple of android benchmarks would be interesting though.
